### ISSUE TITLE
osx support

### ISSUE THREAD

**Issue by xeor** [aslafy-z/helm-git#4]
I'm not 100% sure, but does this support osx?

I'm getting this when trying to use it..

```sh
# helm repo add istio git+https://github.com/istio/istio@install/kubernetes/helm/istio
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
Warning in plugin 'helm-git': git_ref is empty, defaulted to 'master'. Prefer to pin git_ref in URI.
mktemp: illegal option -- p
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
mktemp: illegal option -- p
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
fatal: remote origin already exists.
mktemp: illegal option -- p
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
find: : No such file or directory
./helm-git-plugin.sh: line 64: : No such file or directory
Error: Looks like "git+https://github.com/istio/istio@install/kubernetes/helm/istio" is not a valid chart repository or cannot be reached: plugin "helm-git" exited with error
```

I'm not a big fan of the osx sed, so I can do an `brew install gnu-sed` and get it with `gsed` instead.. But then `helm-git` need to check for that..

Or change the sed to not need the `-r`? Give me some one-liners if you need me to test.
osx got awk as well, and cut, and others :)

**Comment by aslafy-z** [comment]
Thanks for reporting @xeor !

I pushed a commit that should fix it, see #5.
You can give it a try by running:
```sh
helm plugin remove helm-git
helm plugin install https://github.com/aslafy-z/helm-git --version fix/osx-compat
```

Hope it helps!

**Comment by xeor** [comment]
Thanks! (and sorry for the delay...)

The mktemp is still a problem tho, but sed error is gone.

> Warning in plugin 'helm-git': git_ref is empty, defaulted to 'master'. Prefer to pin git_ref in URI.
> mktemp: illegal option -- p
> usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
>        mktemp [-d] [-q] [-u] -t prefix
> mktemp: illegal option -- p
> usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
>        mktemp [-d] [-q] [-u] -t prefix
> fatal: remote origin already exists.
> mktemp: illegal option -- p
> usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
>        mktemp [-d] [-q] [-u] -t prefix
> find: install/kubernetes/helm/istio: No such file or directory
> ./helm-git-plugin.sh: line 65: : No such file or directory
> Error: Looks like "git+https://github.com/istio/istio@install/kubernetes/helm/istio" is not a valid chart repository or cannot be reached: plugin "helm-git" exited with error

mktemp in osx have these options

> OPTIONS
>      The available options are as follows:
> 
>      -d      Make a directory instead of a file.
> 
>      -q      Fail silently if an error occurs.  This is useful if a script
>              does not want error output to go to standard error.
> 
>      -t prefix
>              Generate a template (using the supplied prefix and TMPDIR if set)
>              to create a filename template.
> 
>      -u      Operate in ``unsafe'' mode.  The temp file will be unlinked
>              before mktemp exits.  This is slightly better than mktemp(3) but
>              still introduces a race condition.  Use of this option is not
>              encouraged.

guess `-t` on osx, and `-p` on linux..?

`uname -s` gives `Linux` or `Darwin` on both platforms.. Maybe a logic around that is the solution?

**Comment by aslafy-z** [comment]
I think there is no need for `-p`.
Thanks for the details, I made a fix please try again!

**Comment by xeor** [comment]
great.. The syntax errors are gone :)

Not sure if it's osx related, documentation bug or just me.. But now I'm getting this:

```sh
$ helm repo add istio git+https://github.com/istio/istio@install/kubernetes/helm/istio
Error: Could not find protocol handler for: git+https
```

looking further.. It looks like it is unable to reinstall the plugin :(

```
$ helm plugin --debug install https://github.com/aslafy-z/helm-git --version fix/osx-compat [debug] updating https://github.com/aslafy-z/helm-git
Error: Unable to update repository
```

Tried installing another plugin (helm plugin install https://github.com/technosophos/helm-template) and it worked..

Did you break it? 🤣

**Comment by aslafy-z** [comment]
Just fixed the `mktemp` compatibility. Was using `template` incorrectly (has to put the root path in it). Please have another try!

I'm going to open another issue related to the istio setup.

**Comment by xeor** [comment]
Still unable to install for some reason..

```
helm plugin --debug install https://github.com/aslafy-z/helm-git --version fix/osx-compat
[debug] updating https://github.com/aslafy-z/helm-git
Error: Unable to update repository
```

Not working with other `--version`, tried without, and with `master`..

I can clone the repo normally tho using `git clone`.. 

Are you able to reinstall it?

**Comment by aslafy-z** [comment]
What is your helm version? It might need an update.
Works well at my side with helm 2.12.3, by setting or not the version field.

Try installing again using version 3.0.0 as specified in the README.

**Comment by aslafy-z** [comment]
Looks like it comes from https://github.com/Masterminds/vcs/blob/dfb47aeef3e08fd84f9ba83ab23502bd41634ad2/git.go#L133

Could you try something like 
```sh
mkdir /tmp/helm-git
cd /tmp/helm-git
git init
git remote add origin https://github.com/aslafy-z/helm-git
git fetch origin
git checkout fix/osx-compat
helm plugin install /tmp/helm-git
```

**Comment by xeor** [comment]
Thanks for the tips..

I'm on `v2.12.` as well... Just found that I was missing the `.git`.. Was doing

* helm plugin install https://github.com/aslafy-z/helm-git
instead of
* helm plugin install https://github.com/aslafy-z/helm-git.git

🤦‍♂️

```
helm repo add istio.io git+https://github.com/istio/cni@deployments/kubernetes/install/helm/istio-cni
helm repo add istio git+https://github.com/istio/istio@install/kubernetes/helm
```

works now :) Even tho I didnt install it yet.. :)

**Comment by aslafy-z** [comment]
Mmh, weird as it works here without the `.git`. Might be specific to how git works on osx.

**Comment by xeor** [comment]
`git clone` on osx works with both versions.. I'll check out some more and maybe end up making an issue on the helm repo if I think it's a bug.. Closing this :) Thanks for adding osx support!
